src/main/java/pe/edu/upn/demo/model/entity/SergioSiccha.java, src/main/java/pe/edu/upn/demo/model/repository/SergioSicchaRepository.java, src/main/java/pe/edu/upn/demo/service/SergioSicchaService.java, src/main/java/pe/edu/upn/demo/service/impl/SergioSicchaServiceImpl.java
Profesor le anexo mi parte para que la una al proyecto.
=> N00146030 Sergio Siccha

src/main/java/pe/edu/upn/demo/model/entity/LuizRomero.java
Buenas tardes, Envio mi parte de code profesor Atte: Luiz Romero
=> Enviado por Luiz Romero

src/main/java/pe/edu/upn/demo/model/entity/ErnestoTarazona.java, src/main/java/pe/edu/upn/demo/model/repository/ErnestoTarazonaRepository.java, src/main/java/pe/edu/upn/demo/service/ErnestoTarazonaService.java, src/main/java/pe/edu/upn/demo/service/impl/ErnestoTarazonaServiceImpl.java
=> Enviado por Ernesto Tarazona

src/main/java/pe/edu/upn/demo/model/entity/MarcosRiera.java, src/main/java/pe/edu/upn/demo/model/repository/MarcosRieraRepository.java, src/main/java/pe/edu/upn/demo/service/MarcosRieraService.java, src/main/java/pe/edu/upn/demo/service/impl/MarcosRieraServiceImpl.java
Profesor aquí se encuentra el proyecto
=> N00132734 Marcos Riera

src/main/java/pe/edu/upn/demo/model/entity/Joseph.java, src/main/java/pe/edu/upn/demo/model/repository/JosephRepository.java, src/main/java/pe/edu/upn/demo/service/JosephService.java
=> Enviado por Joseph Poma

src/main/java/pe/edu/upn/demo/model/entity/JohanPizarro.java, src/main/java/pe/edu/upn/demo/model/repository/JohanPizarroRepository.java, src/main/java/pe/edu/upn/demo/service/JohanPizarroService.java, src/main/java/pe/edu/upn/demo/service/impl/JohanPizarroImpl.java
=> Enviado por Johan Pizarro

src/main/java/pe/edu/upn/demo/model/entity/JairRivero.java, src/main/java/pe/edu/upn/demo/model/repository/JairRiveroRepository.java, src/main/java/pe/edu/upn/demo/service/JairRiveroService.java, src/main/java/pe/edu/upn/demo/service/impl/JairRiveroServiceImpl.java
Profesor le envío la parte de mi trabajo.
Jair Rivero
=> Enviado por Jair Rivero

src/main/java/pe/edu/upn/demo/model/entity/SebastianSegura.java, src/main/java/pe/edu/upn/demo/model/repository/SebastianSeguraRepository.java, src/main/java/pe/edu/upn/demo/service/SebastianSeguraService.java, src/main/java/pe/edu/upn/demo/service/impl/SebastianSeguraServiceImpl.java
=> Enviado por Sebastian Segura

src/main/java/pe/edu/upn/demo/model/entity/LuisSuarez.java, src/main/java/pe/edu/upn/demo/model/repository/LuisSuarezRepository.java, src/main/java/pe/edu/upn/demo/service/LuisSuarezService.java, src/main/java/pe/edu/upn/demo/service/impl/LuisSuarezServiceImpl.java
Profe le envío mi parte del trabajo
=> Enviado por Luis Suarez

src/main/java/pe/edu/upn/demo/model/entity/AdrianMorgan.java, src/main/java/pe/edu/upn/demo/model/repository/AdrianMorganRepository.java, src/main/java/pe/edu/upn/demo/service/AdrianMorganService.java, src/main/java/pe/edu/upn/demo/service/impl/AdrianMorganServiceImpl.java
Profe le envio mi parte del trabajo
=> Enviado por Adrian Morgan

src/main/java/pe/edu/upn/demo/model/entity/AndresCastelo.java, src/main/java/pe/edu/upn/demo/model/repository/AndresCasteloRepository.java, src/main/java/pe/edu/upn/demo/service/AndresCasteloService.java, src/main/java/pe/edu/upn/demo/service/impl/AndresCasteloServicempl.java
=>  Enviado por Andres Castelo

src/main/java/pe/edu/upn/demo/model/entity/DiegoTafur.java, src/main/java/pe/edu/upn/demo/model/repository/DiegoTafurRepository.java, src/main/java/pe/edu/upn/demo/service/DiegotafurService.java, src/main/java/pe/edu/upn/demo/service/impl/DiegotafurServiceImpl.java
=> enviado por Diego

src/main/java/pe/edu/upn/demo/model/entity/JeanTalancha.java, src/main/java/pe/edu/upn/demo/model/repository/JeanTalanchaRepository.java, src/main/java/pe/edu/upn/demo/service/JeanTalanchaService.java, src/main/java/pe/edu/upn/demo/service/impl/JeanTalanchaServiceImpl.java
Esta es mi parte del archivo profe
=> Enviado por Jean Talancha

src/main/java/pe/edu/upn/demo/model/entity/LilianCazorla.java, src/main/java/pe/edu/upn/demo/model/repository/LilianCazorlaRepository.java, src/main/java/pe/edu/upn/demo/service/LilianCazorlaService.java, src/main/java/pe/edu/upn/demo/service/impl/LilianCazorlaServiceImpl.java
Profesor le envío mi código presente.
Gracias
Teacher I send to you my code.
Thanks
=> Enviado por Lilian Cazorla

src/main/java/pe/edu/upn/demo/model/entity/GuillermoNakamura.java, src/main/java/pe/edu/upn/demo/model/repository/GuillermoNakamuraRepository.java, src/main/java/pe/edu/upn/demo/service/GuillermoNakamuraService.java, src/main/java/pe/edu/upn/demo/service/impl/GuillermoNakamuraServiceImpl.java
Profe Envio mi Parte desarrollada en clase
GUILLERMO NAKAMURA
=> Enviado por Guillermo Nakamura

src/main/java/pe/edu/upn/demo/model/entity/EnzoCastillo.java, src/main/java/pe/edu/upn/demo/model/repository/EnzoCastilloRepository.java, src/main/java/pe/edu/upn/demo/service/EnzoCastilloService.java, src/main/java/pe/edu/upn/demo/service/impl/EnzoCastilloServiceImpl.java
=> Enviado por Enzo Castillo

src/main/java/pe/edu/upn/demo/model/entity/DiegoVerdeguer.java, src/main/java/pe/edu/upn/demo/model/repository/DiegoVerdeguerRepository.java, src/main/java/pe/edu/upn/demo/service/DiegoVerdeguerService.java, src/main/java/pe/edu/upn/demo/service/impl/DiegoVerdeguerServiceImpl.java
Profesor, le envió mi proyecto para que lo revise. 
Please, don't dissapoint me :(
Thanks :)
=> Enviado por Diego Verdeguer

src/main/java/pe/edu/upn/demo/model/entity/SamuelLazo.java, src/main/java/pe/edu/upn/demo/model/repository/SamuelLazoRepository.java, src/main/java/pe/edu/upn/demo/service/SamuellazoService.java, src/main/java/pe/edu/upn/demo/service/impl/SamuelLazoServiceImpl.java
Profe le envío mi código desarrollado en clase. Gracias
=> Enviado por Samuel Lazo

src/main/java/pe/edu/upn/demo/model/entity/KeyCuevasMelgarejo.java, src/main/java/pe/edu/upn/demo/model/repository/KeyCuevasMelgarejoRepository.java, src/main/java/pe/edu/upn/demo/service/KeyCuevasMelgarejoService.java, src/main/java/pe/edu/upn/demo/service/impl/KeyCuevasMelgarejoServiceImplement.java
Buen día profesor,
Adjunto mi parte.
=> Enviado por Key Cuevas Melgarejo

src/main/java/pe/edu/upn/demo/model/entity/CarlosDiaz.java, src/main/java/pe/edu/upn/demo/model/repository/CarlosDiazRepository.java, src/main/java/pe/edu/upn/demo/service/CarlosDiazService.java, src/main/java/pe/edu/upn/demo/service/impl/CarlosDiazServiceImpl.java
=> Enviado por Carlos Diaz

src/main/java/pe/edu/upn/demo/model/entity/BrijitteGarcia.java, src/main/java/pe/edu/upn/demo/model/repository/BrijitteGarciaRepository.java, src/main/java/pe/edu/upn/demo/service/BrijitteGarciaService.java, src/main/java/pe/edu/upn/demo/service/impl/BrijitteGarciaServiceImpl.java
PROFE LE ENVÍO MI CÓDIGO PRESENTE
=> Enviado por Brijitte Garcia

src/main/java/pe/edu/upn/demo/model/entity/JosselynSanchez.java, src/main/java/pe/edu/upn/demo/model/repository/JosselynSanchezRepository.java, src/main/java/pe/edu/upn/demo/service/JosselynSanchezService.java, src/main/java/pe/edu/upn/demo/service/impl/JosselynSanchezServiceImpl.java
Profesor le envió mi código presente
=> Enviado por josselyn sanchez

src/main/java/pe/edu/upn/demo/model/entity/JeanPierreConde.java, src/main/java/pe/edu/upn/demo/model/repository/JeanPierreCondeRepository.java, src/main/java/pe/edu/upn/demo/service/JeanPierreCondeService.java, src/main/java/pe/edu/upn/demo/service/impl/JeanPierreCondeServiceImpl.java
Profesor le envío mi código presente ga
=> Enviado por Jean Pierre Conde

src/main/java/pe/edu/upn/demo/model/entity/DiegoNoblecilla.java, src/main/java/pe/edu/upn/demo/model/repository/DiegoNoblecillaRepository.java, src/main/java/pe/edu/upn/demo/service/DiegoNoblecillaService.java, src/main/java/pe/edu/upn/demo/service/impl/DiegoNoblecillaServiceImpl.java
=> Enviado por Diego Noblecilla

src/main/java/pe/edu/upn/demo/model/entity/JosuePacherres.java, src/main/java/pe/edu/upn/demo/model/repository/JosuePacherresRepository.java, src/main/java/pe/edu/upn/demo/service/JosuePacherresService.java, src/main/java/pe/edu/upn/demo/service/impl/JosuePacherresServiceImpl.java
=> Enviado por Josué Pacherres
